sequenceDiagram
    title add quantity product
    actor user 
    participant MkDelivery
    participant User
    participant Cart 
    user ->> MkDelivery:insert quantity of cart item
    MkDelivery ->> User :get_user
    User ->> Cart : get_cart 
    Cart ->> Cart : increase queantity(productname,queatity)
    Cart -->> User :update cart 
    User -->> MkDelivery: Update User's Cart
    MkDelivery -->> user: show cart new quatity of item

