sequenceDiagram
    title add quantity cart item
    actor use 
    participant system
    participant user
    participant cart 
    system ->> user :get user(username) 
    user ->> cart : get cart 
    cart ->> cart : increase quantity(productname,queatity)
    cart -->> user :update cart 
    user -->> system: Update User's Cart

