sequenceDiagram
    title remove product
    actor user 
    participant MkDelivery
    participant User
    participant Cart 
    user ->> MkDelivery:click remove item in cart
    MkDelivery ->> User :get_user
    User ->> Cart : get_cart 
    Cart ->> Cart : remove_cart_item
    Cart -->> User :update cart 
    User -->> MkDelivery: Update User's Cart
    MkDelivery -->> user: show cart
