sequenceDiagram
    title login
    actor user
    participant system
    participant user
    user ->> system :insert email password
    system ->> user :get usert(email)
    alt user is none
        user-->>system: login fail
    alt user password wrong
        user -->> system : login fail
    else 
        user->>system: return user name
    system --> user :login status
