sequenceDiagram
    title login
    actor A
    participant system
    participant user
    A -> system :insert email password
    system -> user :get usert(email)
    alt user is none
        userb-->>system: login fail
    alt user password wrong
        user -->> system : login fail
    else 
        user->>system: return user name
    system --> A :login status
