sequenceDiagram
    title login
    actor user
    participant MkDelivery
    participant User
    user ->> MkDelivery :insert email,password
    MkDelivery ->> User :get_usert
    alt User is None
        User -->> MkDelivery: Login Failed
    else
        alt Password is wrong
            User -->> MkDelivery: Login Failed
        else
            User -->> MkDelivery: log in success,Return user name
        end
    end
    MkDelivery --> user: return username




