sequenceDiagram
    title register
    actor A
    participant system
    participant customer
    participant account
    
    A ->> system:insert name,email,password,phone num
    system ->> customer :add user
    customer ->>  account :create account
    account ->> account : create new account
    account -->> customer :return account
    customer -->> customer :return new user
    customer --> system: udate user list
    system --> A :show new user



