sequenceDiagram
    title register
    actor user
    participant MkDelivery
    participant Customer
    participant Account
    
    user ->> MkDelivery:insert name,email,password,phone num
    MkDelivery ->> Customer :add user
    Customer ->>  Account :create account
    Account ->> Account : create new account
    Account -->> Customer :return account
    Customer -->> Customer :create new user
    Customer -->> MkDelivery: update user list
    MkDelivery -->> user :show new user



