sequenceDiagram
    title register
    participant system
    participant user
    actor A
    A -> system:insert name,email,password,phone num
    system -> user :add user
    user -->>  system :return new user
    system -> system :update user_list
    system -> user :get user data
    user --> system: returen user data
    system --> A :return data


sequenceDiagram
    title login
    actor A
    participant system
    participant user
    A -> system :insert email password
    system -> user :get usert(email)
    alt user is none
        userb->>system: login fail
    alt user password wrong
        user ->> system : login fail
    else 
        user->>system: return user name
    system --> A :login success


