sequenceDiagram
    title creat order
    actor a
    participant system 
    participant user
    participant user
    a ->> system :send username 
    system ->> user :get user(username)
    system ->> order: build ubject order(address, total_cost,status,username_d)
    order -> system: return(order)
    order -> a: show order

sequenceDiagram
    title add to cart
    participant system 
    participant cart
    actor a 
    a ->> system:return username
    system ->> cart:get cart(username)
    cart ->> cart: add cart item 
    cart -->> system : return cart 
    system --> a :show cart 








