sequenceDiagram register
    title register
    participant A as Actor
    participant system
    participant user as User
    
    A ->> system: insert name, email, password, phone number
    system ->> user: add user
    user -->> system: return new user
    system ->> system: update user_list
    system ->> user: get user data
    user -->> system: return user data
    system -->> A: return data


