sequenceDiagram
    title read category list
    actor user
    participant MkDelivery
    participant ProductCategory
    participant Product

    user ->> MkDelivery: click to see product info
    MkDelivery ->> ProductCategory:get_category
    ProductCategory ->> Product: get_product
    Product -->> ProductCategory: return product info 
    ProductCategory -->> MkDelivery:return product info
    MkDelivery -->> user: show product info


