sequenceDiagram
    title read all product in category
    actor user
    participant MkDelivery
    participant ProductCategory

    user ->> system: click to see category'product
    MkDelivery ->> ProductCategory:get_category
    loop for product in category
        ProductCategory -->> MkDelivery: return category's products
    MkDelivery -->> user: show all product in category


