sequenceDiagram
    title read all product in category
    actor user
    participant MkDelivery
    participant ProductCategory

    user ->> MkDelivery: click to see category's product
    MkDelivery ->> ProductCategory:get_category
    loop for product in category
        ProductCategory -->> MkDelivery: return category's products
    end
    MkDelivery -->> user: show all products in category
