sequenceDiagram
    title read category list
    actor user
    participant MkDelivery

    user ->> MkDelivery: click to see category
    MkDelivery ->> MkDelivery:get category list
    MkDelivery -->> user: show all category

