sequenceDiagram
    title edit profile 
    actor user
    participant MkDelivery
    participant User

   
    user ->> MkDelivery:insert name, phone, birthday, address for edit profile 
    MkDelivery ->> User:get_user
    User ->> User :edit_profile(name, phone, birthday, address)
    User -->> MkDelivery:update new profile 
    MkDelivery --> user:show new profile 

    
    