sequenceDiagram
    title get current user
    actor user
    participant MkDelivery
    participant User
    participant Account
   
    user ->> MkDelivery:click to user
    MkDelivery ->> User:get_user
    User ->> Account:get_account
    Account -->> User :return user's accout
    User -->> MkDelivery:return User
    MkDelivery -->> user:display user

    
    