sequenceDiagram
    title get current user
    actor user
    participant MkDelivery
    participant User
    participant Account
   
    user ->> MkDelivery:click button
    MkDelivery ->> User:get_user
    User -->> MkDelivery:return User
    MkDelivery ->> User:get_user
    User ->> Account:get_account
    Account -->> User:return accunt
    User -->> MkDelivery:return account
    MkDelivery -->> user:show user and account

    
    