sequenceDiagram
    title read user list 
    actor user
    participant MkDelivery
    participant User
    participant Account

    user ->> MkDelivery:see all user
    MkDelivery ->> MkDelivery:get_all_user
    MkDelivery -->> user:show all user
    


    

    