sequenceDiagram
    title add product
    actor admin
    participant MkDelivery
    participant ProductCategory
    participant Product
    admin ->> MkDelivery: insert category,name,imageUrl,price,description,calories,type
    MkDelivery ->> ProductCategory:get_category
    ProductCategory ->> Product:add_product
    Product ->> Product:create new product
    Product -->> ProductCategory:return new product
    ProductCategory -->> MkDelivery:return category's new product
    MkDelivery -->> admin:show new product


    
    
    
