sequenceDiagram
    title add user
    actor admin
    participant system
    participant user
    participant category
    admin ->> system: send name,email,password,phone,birthday
    system ->> user:add user
    user -->> user : create new user
    user -->> system: return new user
    system -->> admin: show new user