sequenceDiagram
    title add product
    actor admin
    participant system
    participant user
    participant category
    admin ->> system: send username to add product
    system ->> category:get category
    category ->> product:add product
    product ->> product:create new product
    product -->> category:return new product
    category -->> system:return category's new product
    system -->> admin:show new product


    
    
    
