sequenceDiagram
    title add user
    actor admin
    participant MkDelivery
    participant Customer
    participant Account
    admin ->> MkDelivery: insert name,email,password,phone,birthday
    MkDelivery ->> Customer:add user
    Customer ->> Account: get account
    Account ->> Account : create account 
    Account ->> Customer : return account 
    Customer -->> Customer : create new user
    Customer -->> MkDelivery: return new user
    MkDelivery -->> admin: show new user