sequenceDiagram
    title add category
    actor admin
    participant MkDelivery
    participant ProductCategory
    admin ->> MkDelivery: insert name,imageUrl
    MkDelivery ->> ProductCategory:add_category
    ProductCategory ->> ProductCategory:create new category
    ProductCategory -->> MkDelivery : return new category 
    MkDelivery -->> admin:show new category
    
