sequenceDiagram
    title category
    actor admin
    participant system
    participant user
    participant category
    admin ->> system: send username to add category
    system ->> category:add category
    category ->> category:create new category
    category -->> system : return new category 
    system -->> admin:show new category
    
